services:
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: warehouse-laravel
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
    networks:
      - laravel-net

  mysql:
    image: mysql:8
    container_name: warehouse-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
      MYSQL_USER: user
      MYSQL_PASSWORD: null
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net: